import type {
  ClubCard,
  FutCardPropDataTypes,
  FutStats,
  RankedPosition,
  RankedPosition_Type,
} from "@/lib/types";

import type { PlayerAttributeCategory } from "../components/pages/player/Glance";

export const rankPositions: RankedPosition[] = [
  {
    shortlabel: "GK",
    positions: ["GK"],
    label: "Goalkeeper",
    region: "GK",
    id: "0",
    rankedPosition: "GK",
  },
  {
    shortlabel: "CB",
    positions: ["CB"],
    label: "Centerback",
    region: "DEF",
    id: "5",
    rankedPosition: "CB",
  },
  {
    shortlabel: "LB/RB",
    positions: ["LB", "RB"],
    label: "Fullback",
    region: "DEF",
    id: "3",
    rankedPosition: "FB",
  },
  {
    shortlabel: "LWB/RWB",
    positions: ["LWB", "RWB"],
    label: "Wingback",
    region: "DEF",
    id: "2",
    rankedPosition: "WB",
  },
  {
    shortlabel: "CDM",
    positions: ["CDM"],
    label: "Defensive Midfielder",
    region: "MID",
    id: "10",
    rankedPosition: "DM",
  },
  {
    shortlabel: "CM",
    positions: ["CM"],
    label: "Center Midfielder",
    region: "MID",
    id: "14",
    rankedPosition: "CM",
  },
  {
    shortlabel: "LM/RM",
    positions: ["LM", "RM"],
    label: "Wide Midfielder",
    region: "MID",
    id: "12",
    rankedPosition: "WM",
  },
  {
    shortlabel: "CAM",
    positions: ["CAM", "LAM", "RAM"],
    label: "Attacking Midfielder",
    region: "MID",
    id: "18",
    rankedPosition: "AM",
  },
  {
    shortlabel: "LW/RW",
    positions: ["LW", "RW"],
    label: "Winger",
    region: "ATT",
    id: "23",
    rankedPosition: "W",
  },
  {
    shortlabel: "CF",
    positions: ["CF", "LF", "RF"],
    label: "Forward",
    region: "ATT",
    id: "21",
    rankedPosition: "F",
  },
  {
    shortlabel: "ST",
    positions: ["ST"],
    label: "Striker",
    region: "ATT",
    id: "26",
    rankedPosition: "ST",
  },
];

export const attributeMappingByRankedPosition: Record<
  RankedPosition_Type,
  (keyof FutStats)[]
> = {
  GK: [
    "gkdiving",
    "gkhandling",
    "gkreflexes",
    "gkpositioning",
    "reactions",
    "gkkicking",
  ],
  SW: [
    "standingtackle",
    "marking",
    "slidingtackle",
    "headingaccuracy",
    "strength",
    "interceptions",
    "aggression",
    "shortpassing",
    "reactions",
    "ballcontrol",
    "jumping",
  ],
  CB: [
    "standingtackle",
    "marking",
    "interceptions",
    "slidingtackle",
    "headingaccuracy",
    "strength",
    "aggression",
    "reactions",
    "shortpassing",
    "ballcontrol",
    "jumping",
    "sprintspeed",
  ],
  FB: [
    "slidingtackle",
    "interceptions",
    "standingtackle",
    "crossing",
    "reactions",
    "stamina",
    "marking",
    "sprintspeed",
    "shortpassing",
    "ballcontrol",
    "acceleration",
    "headingaccuracy",
  ],
  WB: [
    "crossing",
    "interceptions",
    "slidingtackle",
    "shortpassing",
    "stamina",
    "ballcontrol",
    "standingtackle",
    "reactions",
    "marking",
    "sprintspeed",
    "dribbling",
    "acceleration",
  ],
  DM: [
    "interceptions",
    "shortpassing",
    "standingtackle",
    "ballcontrol",
    "longpassing",
    "marking",
    "reactions",
    "stamina",
    "slidingtackle",
    "aggression",
    "vision",
    "strength",
  ],
  CM: [
    "shortpassing",
    "ballcontrol",
    "vision",
    "longpassing",
    "reactions",
    "dribbling",
    "stamina",
    "positioning",
    "standingtackle",
    "interceptions",
    "longshots",
    "finishing",
  ],
  WM: [
    "dribbling",
    "ballcontrol",
    "shortpassing",
    "crossing",
    "positioning",
    "acceleration",
    "reactions",
    "vision",
    "sprintspeed",
    "finishing",
    "longpassing",
    "stamina",
  ],
  AM: ["dribbling", "vision", "ballcontrol", "short_passing", "finishing"],
  W: [
    "dribbling",
    "ballcontrol",
    "finishing",
    "shortpassing",
    "positioning",
    "crossing",
    "reactions",
    "acceleration",
    "vision",
    "sprintspeed",
    "longshots",
    "agility",
  ],
  F: [
    "ballcontrol",
    "dribbling",
    "positioning",
    "finishing",
    "reactions",
    "shortpassing",
    "vision",
    "shotpower",
    "acceleration",
    "sprintspeed",
    "longshots",
    "headingaccuracy",
  ],
  ST: [
    "finishing",
    "positioning",
    "headingaccuracy",
    "ballcontrol",
    "shotpower",
    "reactions",
    "dribbling",
    "strength",
    "sprintspeed",
    "shortpassing",
    "acceleration",
    "longshots",
    "volleys",
  ],
};

export const attributeMappingByCategory: Record<
  PlayerAttributeCategory,
  (keyof FutStats)[]
> = {
  attacking: [
    "positioning",
    "finishing",
    "headingaccuracy",
    "longshots",
    "shotpower",
    "volleys",
  ],
  skill: [
    "dribbling",
    "curve",
    "freekickaccuracy",
    "longpassing",
    "ballcontrol",
  ],
  movement: ["acceleration", "sprintspeed", "agility", "reactions", "balance"],
  power: ["shotpower", "jumping", "stamina", "strength", "longshots"],
  mentality: [
    "aggression",
    "interceptions",
    "positioning",
    "vision",
    "penalties",
  ],
  defending: [
    "strength",
    "aggression",
    "interceptions",
    "marking",
    "standingtackle",
    "slidingtackle",
  ],
};

export const FutSpinRatings = [90, 40, 50, 60, 70, 80, 83, 86];

export const examplePlayerData:FutCardPropDataTypes = {
  "player_name": "Haaland",
  "futid": 184788461,
  "playerid": 239085,
  "overallrating": 99,
  "nationality": 36,
  "prefpos1": "ST",
  "team_id": 10,
  "age": 24,
  "height": 195,
  "weight": 94,
  "attackingWorkRate": "M",
  "defensiveWorkRate": "M",
  "weakfootabilitytypecode": 5,
  "skillmoves": 5,
  "carrer_player": true,
  "club_img_url": "https://fifarosters.com/assets/clubs/fifa24/10.png",
  "league_img_url": "https://fifarosters.com/assets/leagues/fifa24/13.png",
  "chemistrytype": "basic",
  "isdynamicportrait": true,
  "player_img_url": "https://www.fifarosters.com/assets/players/fifa24/dynamic/184788461.png",
  "img_onerror": "https://www.fifarosters.com/assets/players/fifa24/faces/239085.png",
  "rating": {
    "pac": 98,
    "sho": 99,
    "pas": 90,
    "dri": 93,
    "def": 58,
    "phy": 98
  },
  "fut_stats": {
    "acceleration": 96,
    "sprintspeed": 99,
    "agility": 91,
    "balance": 90,
    "jumping": 99,
    "stamina": 93,
    "strength": 99,
    "reactions": 99,
    "aggression": 99,
    "interceptions": 56,
    "positioning": 99,
    "vision": 99,
    "ballcontrol": 95,
    "crossing": 70,
    "dribbling": 92,
    "composure": 99,
    "finishing": 99,
    "freekickaccuracy": 91,
    "headingaccuracy": 99,
    "longpassing": 77,
    "shortpassing": 99,
    "marking": 49,
    "shotpower": 99,
    "longshots": 99,
    "standingtackle": 61,
    "slidingtackle": 38,
    "volleys": 99,
    "curve": 99,
    "penalties": 99
  },
  "nation_img_url": "https://fifarosters.com/assets/nations/fifa17/36.png",
  "foot": "left",
  "alt_positions": [
    "ST"
  ],
  "playstyles": [
    "Rapid",
    "Finesse Shot",
    "Aerial",
    "Press Proven"
  ],
  "futlabel": "Futties",
  "futcolors": [
    16776446,
    16776446,
    16776446,
    16776446,
    16776446,
    16776446,
    16720799,
    16756187,
    15132390
  ],
  "background_img_url_l": "https://fifarosters.com/assets/cards/fifa24/cards_bg_e_1_9_0.png",
  "background_img_url_s": "https://fifarosters.com/assets/cards/fifa24/cards_bg_s_1_9_0.png",
  teamname: "",
  nationname: "",
  leaguename: ""
}

export const defaultClub: ClubCard = {
  id: 1,
  label: 'FC Barchleona',
  img: 'https://www.fifarosters.com/assets/clubs/fifa24//241.png',
  rating: 90,
}

const DATA = {
  rankPositions,
  attributeMappingByCategory,
  attributeMappingByRankedPosition,
  FutSpinRatings
};

export default DATA;
